# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role-to-assume: arn:aws:iam::590130834747:role/my-github-actions-role-2022
          aws-region: us-east-1
      - name: Cypress run
        continue-on-error: false
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: false
      - name: Merge results to json
        if: always()
        run: npx mochawesome-merge cypress/results/*.json > cypress/results/output.json
      - name: Generate html -page
        if: always()
        run: npx marge cypress/results/output.json --reportDir cypress/results/ --inline
   
